version: "3.7"
services:
  #dados para crição do container do mysql
  mysql_db:
    image: "mysql:8.0" #imagem vem do dockerhub, equivale ao from
    container_name: mysqlserver #nomeando container
    ports: # redirecionando as portas
      - "3306:3306" # primeira meu pc e seunda porta container
    environment: #variaveis de ambientes do mysql
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: admin
      MYSQL_PASSWORD: DigitalHouse2022
      MYSQL_ROOT_PASSWORD: DigitalHouse2022
    volumes: #meu hd externo para o container
      - db_mysql:/var/lib/mysql
    networks: # uma rede entre os container
      - servers
  ##fim do mysql

volumes:
  db_mysql:

networks:
  servers:
    driver: bridge