- hosts: backend
  become: yes
  tasks:
# 1
  - name: "System : instalando o mvn"
    shell:
      cmd: "sudo mvn install"
      chdir: /home/ubuntu/backend
# 2
  - name: " System : Executando o docker-compose da aplicacao java/backend"
    become: true
    shell:
      cmd: "docker-compose -f docker-compose-java.yml up -d"
      chdir: /home/ubuntu/backend # mesma pasta da linha 79 no playbook.yaml