- hosts: backend
  become: yes
  tasks:
  # 1
  - name: Clonando o Repositorio do Projeto Ecommerce em JAVA
    ansible.builtin.git:
      # o repositório que vamos clonar
      repo: https://github.com/cypherbold/DHBackEnd.git  # definir o repositorio do backend
      # onde vamos clonar
      dest: /home/ubuntu/backend # mesmo nome do repositorio
      # qual é a branch que vamos clonar
      version: main
      # aqui estopu dizendo que quero seja feito update sempre que rodar a tarefa
      update: yes
      # force pq eu quero, baixa e pronto. eu mandei.
      force: yes
  # 3
  - name: Rodando docker-compose mysql
    become: true
    shell:
      cmd: "docker-compose -f docker-compose-mysql.yml up -d"
      chdir: /home/ubuntu/backend # mesma pasta da linha 79
  # Fim